---
title: "Time Series Homework 4"
author: "Team 6 - Oliver Chen, Hannah Enck, Jamil Gracia, Ava Klissouras"
date: "2025-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

Load libraries.

```{r}
library(tsibble)
library(tidyverse)
library(ggplot2)
library(forecast)
library(fable)
library(fpp3)
library(tseries)
```


Read in data.

```{r}
data_path = "https://raw.githubusercontent.com/sjsimmo2/TimeSeries/refs/heads/master/energy_F2025.csv"
energy <- readr::read_csv(data_path, show_col_types=FALSE)
```

Roll up data.

```{r}
energy_daily <- energy %>%
  mutate(new_datetime = mdy_hm(datetime_beginning_ept),
         date = as_date(new_datetime)) %>%
  group_by(date) %>%
  summarise(daily_total = sum(mw))

```


Train test split.

```{r}
#Train: data from August 2018 - August 2023
train <- energy_daily %>%
  filter(date >= as.Date("2018-08-01") & date < as.Date("2023-08-01"))

train.ts = train %>%
  as_tsibble(index = date)

#Validation: data from September 2023 - August 2024
validation <- energy_daily %>%
  filter(date >= as.Date("2023-08-01") & date < as.Date("2024-08-01"))

validation.ts = validation %>%
  as_tsibble(index = date)

#Test: data from September 2024 - August 2025
test <- energy_daily %>%
  filter(date >= as.Date("2024-08-01") & date < as.Date("2025-08-01"))

test.ts = test %>%
  as_tsibble(index = date)
```

# Analysis

## Exponential Smoothing Model (ESM)

### Performing STL decomposition on training data to assess trend/seasonality
```{r}
dcmp = train.ts %>% model (stl = STL (daily_total))
components(dcmp) %>% autoplot() + theme_classic()
```

```{r}
train.ts %>% 
  features(daily_total, feat_stl, .period = "year")

train.ts %>% 
  features(daily_total, feat_stl, .period = 7)

#Yearly seasonal strength is much stronger than weekly, so we will just stick with year

```


### Fitting models
```{r}
esm_fit <- train.ts |>
  model(
    #Just weekly seasonality since ESM does not support periods longer than 24 (i.e. year would be 365 since we have daily data)
    'HWAddWeek' = ETS(daily_total ~ error("A") + trend("A") + season("A", period="week")),
    'HWMultWeek' = ETS(daily_total ~ error("M") + trend("A") + season("M", period="week")),
    'NoTrendWeek' = ETS(daily_total ~ error("A") + trend("N") + season("A", period="week"))
  )
```

```{r}
esm_fc <- esm_fit %>%
  fabletools::forecast(h = nrow(validation))
fabletools::accuracy(esm_fc, validation.ts)
```

```{r}
#Search for best one
esm_auto <- train.ts %>%
  model(ETS(daily_total))

report(esm_auto) #MNA

auto_fc <- esm_auto %>%
  fabletools::forecast(h = nrow(validation)-1)
fabletools::accuracy(auto_fc, validation.ts)

#Worse than the ones we did manually

```

### Actual vs. Forecasted Plot

```{r}
#Best model of all the ones above was Holt-Winters additive

#Get forecast
HW_add <- train.ts |>
  model(
    ETS(daily_total ~ error("A") + trend("A") + season("A", period="week"))
  )
ESM_fc <- HW_add %>%
  fabletools::forecast(h = nrow(validation)-1)

ggplot() + geom_line(data = ESM_fc, aes(x=date, y=.mean, color = "Forecast")) + 
  geom_line(data = validation.ts, aes(x=date, y=daily_total, color = "Actual"))+
  labs(x="Month", y="Megawatts", title="Total Daily Energy Consumption", color = "Series") + 
  scale_color_manual (values=c("Actual"="black","Forecast" = "hotpink" ))
```

## ARIMA

### Seasonal ARIMA

```{r}

```


### Forecast on Validation

```{r}

```


### Model Accuracy

```{r}

```


### Actual vs. Forecasted

```{r}

```
